# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit predictset.Rmd to modify this file

## ----setup, include = FALSE---------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,
                      fig.align = "center", out.width = "100%")


## ----hetero, fig.cap = "Split-conformal prediction intervals on a one-dimensional heteroscedastic problem at target coverage 0.90. Grey points show 400 training observations drawn from a sine signal with heteroscedastic Gaussian noise. Shaded bands are 200 test-point intervals from \\texttt{conformal\\_split()} with \\texttt{score\\_type = \"absolute\"} (left, empirical coverage 0.890, mean width 5.45) and \\texttt{score\\_type = \"normalized\"} (right, empirical coverage 0.905, mean width 5.34). The normalised scoring produces narrower intervals where noise is low without losing coverage.", fig.alt = "A two-panel scatter plot of 400 training points under a sinusoidal signal with noise that grows with the input. The left panel shows absolute-residual conformal intervals as a constant-width band around the fitted curve. The right panel shows normalised-residual intervals that narrow near the left edge where noise is low and widen toward the right where noise is higher. Both panels report empirical coverage near 0.90 and similar mean interval widths."----
knitr::include_graphics("figures/fig1_heteroscedastic.pdf")


## ----compare-tab--------------------------------------------------------------
compare_tab <- data.frame(
  Method = c("Split conformal", "CV+", "Jackknife+"),
  Target = c(0.90, 0.90, 0.90),
  `Empirical coverage` = c(0.925, 0.907, 0.905),
  `Mean width` = c(4.340, 4.016, 4.027),
  check.names = FALSE
)
knitr::kable(
  compare_tab,
  caption = "Empirical coverage and mean interval width across three regression methods on a common sample. Synthetic data with 500 training points, 400 test points, and Gaussian noise with unit standard deviation. Target coverage 0.90. The CV+ variant is fit with ten folds; Jackknife+ is leave-one-out. All three methods reach target coverage; the cross-validated variants achieve meaningfully tighter intervals.",
  label = "compare",
  booktabs = TRUE,
  align = "lrrr"
)


## ----compare, fig.cap = "Mean prediction-interval width across split, CV+, and Jackknife+ on a common regression task. Bars show mean width; text above each bar reports empirical coverage on a 400-point held-out test set. Target coverage is 0.90. CV+ and Jackknife+ recover roughly 9 per cent width relative to split conformal by using all training data for both fitting and calibration.", fig.alt = "A bar chart with three bars, one each for split conformal, CV+, and Jackknife+. The split conformal bar is the tallest at about 4.34 units of mean interval width; the CV+ and Jackknife+ bars are nearly identical and about 9 per cent shorter, at around 4.02 units. Each bar has its empirical coverage labelled above it: 0.925 for split, 0.907 for CV+, and 0.905 for Jackknife+."----
knitr::include_graphics("figures/fig2_compare.pdf")


## ----aps, fig.cap = "Mean APS prediction-set size grouped by predictive entropy decile, three-class synthetic task, target coverage 0.90. Training set of 600 observations with three classes separable up to an overlap region around the decision boundary; 300 test points scored by \\texttt{conformal\\_aps()} wrapping a 200-tree \\texttt{ranger} classifier. Difficulty deciles are computed from the entropy of the classifier softmax output. Mean set size rises monotonically with entropy, from near one in the easy deciles to near three at the decision boundary.", fig.alt = "A bar chart with ten bars, one per entropy decile. Mean prediction-set size starts at just above one for the lowest-entropy decile, rises gradually across the middle deciles, and reaches close to three for the highest-entropy decile. The monotonic rise shows APS producing larger sets for harder, higher-entropy test points."----
knitr::include_graphics("figures/fig3_aps_sets.pdf")


## ----mond, fig.cap = "Group-conditional empirical coverage on a two-group heteroscedastic regression task, target 0.90. Training set 1200 points, test set 400 points, conditional standard deviation 3 for the high-noise group and 0.75 for the low-noise group. Dashed line marks target coverage. Split conformal (orange) achieves marginal coverage by under-covering the high-noise group. Mondrian (blue) computes calibration quantiles per group and delivers the target within each subgroup.", fig.alt = "A grouped bar chart with two groups on the horizontal axis (low noise and high noise) and two bars per group (split conformal in orange and Mondrian in blue). A horizontal dashed line at 0.90 marks target coverage. For the low-noise group, split conformal over-covers and sits well above the dashed line; Mondrian sits on the dashed line. For the high-noise group, split conformal falls below the dashed line while Mondrian again sits on it, showing that Mondrian delivers the target within each subgroup."----
knitr::include_graphics("figures/fig4_mondrian.pdf")


## ----weighted, fig.cap = "Empirical coverage on a shifted test set at target 0.90. Training covariates standard normal; test covariates normal with mean 1.5. Outcome is a linear signal with heteroscedastic noise. Under this covariate shift, standard split conformal loses coverage by more than ten percentage points; weighted conformal using the exact likelihood-ratio weights recovers close to target coverage.", fig.alt = "A bar chart with two bars. The first bar, for standard split conformal under covariate shift, falls well below the 0.90 target, around 0.78. The second bar, for weighted conformal using likelihood-ratio weights, sits very close to 0.90. A dashed horizontal line marks the 0.90 target for reference."----
knitr::include_graphics("figures/fig5_weighted.pdf")


## ----compas, fig.cap = "Empirical per-race coverage from marginal APS and Mondrian APS on COMPAS two-year recidivism, target 0.90. Data: ProPublica COMPAS dataset (6167 defendants after standard ProPublica screening). Caucasian and African-American subgroups shown. Dashed line at 0.90 marks target coverage. Marginal APS over-covers both groups by including both outcome classes in the prediction set frequently enough to hit 100 per cent empirically. Mondrian APS computes a separate calibration quantile per group and tracks the 0.90 target more tightly on each.", fig.alt = "A grouped bar chart with two groups on the horizontal axis (Caucasian and African-American) and two bars per group (marginal APS and Mondrian APS). A horizontal dashed line at 0.90 marks target coverage. The marginal APS bars reach 1.00 in both groups, over-covering. The Mondrian APS bars sit close to the dashed line at 0.90 in both groups, showing tight tracking of the target within each subgroup."----
knitr::include_graphics("figures/fig6_compas.pdf")

